// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8w-tsQFfQP3PXmMZiMnJ4cr2uQrPSasU',
    appId: '1:359415892921:web:bea9410a2b47009b260468',
    messagingSenderId: '359415892921',
    projectId: 'careq-12302',
    authDomain: 'careq-12302.firebaseapp.com',
    storageBucket: 'careq-12302.firebasestorage.app',
    measurementId: 'G-EHYE0R79TX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzPx2FycIbfVQh0IXBo_-K-Lts1mfXSd8',
    appId: '1:359415892921:android:79616345cfe5b3e0260468',
    messagingSenderId: '359415892921',
    projectId: 'careq-12302',
    storageBucket: 'careq-12302.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcMJrQYG9Ga3DLxb4BzE6KgVRV4-EuXw',
    appId: '1:359415892921:ios:c838df8c6ed1de1e260468',
    messagingSenderId: '359415892921',
    projectId: 'careq-12302',
    storageBucket: 'careq-12302.firebasestorage.app',
    iosBundleId: 'com.example.careq',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcMJrQYG9Ga3DLxb4BzE6KgVRV4-EuXw',
    appId: '1:359415892921:ios:c838df8c6ed1de1e260468',
    messagingSenderId: '359415892921',
    projectId: 'careq-12302',
    storageBucket: 'careq-12302.appspot.com',
    iosBundleId: 'com.example.careq',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8w-tsQFfQP3PXmMZiMnJ4cr2uQrPSasU',
    appId: '1:359415892921:web:6b869e786bc3573b260468',
    messagingSenderId: '359415892921',
    projectId: 'careq-12302',
    authDomain: 'careq-12302.firebaseapp.com',
    storageBucket: 'careq-12302.firebasestorage.app',
    measurementId: 'G-LBZLRNVX1N',
  );
}